@host = http://192.168.1.235:3005

# /
GET {{host}}/
content-type: application/json

{
}
###

# /hello
GET {{host}}/hello
content-type: application/json

{
}
###

# 取得目前時間
GET {{host}}/now_time
content-type: application/json

{
}
###

# 取得設定版本 - 全部
POST {{host}}/getSettingVersion
content-type: application/json
appName: "ReactAdmin"

{
}
###

# 取得設定版本 - 單一
POST {{host}}/getSettingVersion
content-type: application/json
appName: "ReactAdmin"

{
    "data_type": "weight_training"
}
###

# posts
POST {{host}}/posts/list
content-type: application/json
appName: "ReactAdmin"

{
}
###

# 取得設定版本
POST {{host}}/settingVersion/list
content-type: application/json
appName: "ReactAdmin"

{
}
###